### ISSUE TITLE
Consider using libplctag.NativeImport?

### ISSUE THREAD

**Issue by timyhac** [GitHubDragonFly/AB-Modbus-Master#1]
Hey there friend!

Was wondering if you have considered using the wrapper from the libplctag organization: https://www.nuget.org/packages/libplctag.NativeImport/
https://github.com/libplctag/libplctag.NET

The benefit in my view is that you won't need to have library embed/extraction/dll interfacing logic in your solution, you can use what is provided there. I also usually update this wrapper within a few hours of a release of the core library by Kyle unless there are API changes.

If not, are there any features lacking in this wrapper that would prevent you from using it?

timyhac

**Comment by GitHubDragonFly** [comment]
I do follow what you guys do, to a degree, and using your wrapper will be something to consider eventually.

This AB-Modbus-Master project is as it is because it started a while ago when I was experimenting with embedding unmanaged library into the executable file. It is not perfect but it appears to be highly functional for those features that I could test myself.

One day I might even convert this project to use your wrapper instead.

**Comment by timyhac** [comment]
No probs!

Extracting the native library is precisely what the libplctag.NativeImport package does. I've found that it works quite well for Win32 apps (i.e. Winforms and WPF), but for UWP and other types of apps where there is restricted file system access it doesn't work as well.

There is an [open issue](https://github.com/libplctag/libplctag.NET/issues/137) against that package to deal with that.
